language: node_js
cache:
  directories:
  - bower_components
  - node_modules
env:
  global:
    secure: LTeizUOW9zSnDFFU7fY1NZ9wl6H2uEUa80rQ+qnfgw61Lix3D1oFnshLy9X//O8PclkSKmJx1x4WHuCRdDX8yeFdQr0svUa3rRkLjUli2m2hIueUA6gGxto80M/I/v5wfROqJwtrejJs6PjgZYiJMJIyoDE5Vl8B5SGR7a1Tp9g=
sudo: false
after_success: codeclimate < tests/coverage/report.lcov
