language: node_js
node_js: --lts
addons:
  chrome: stable
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_success:
  # CC_TEST_REPORTER_ID environment variable must be set in Travis CI project settings
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
cache:
  directories:
  - bower_components
  - node_modules
before_deploy:
  - npm run build
deploy:
  provider: pages
  local-dir: dist
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache/bower
