language: node_js
node_js: 4
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  global:
  - CXX=g++-4.8
  - secure: LTeizUOW9zSnDFFU7fY1NZ9wl6H2uEUa80rQ+qnfgw61Lix3D1oFnshLy9X//O8PclkSKmJx1x4WHuCRdDX8yeFdQr0svUa3rRkLjUli2m2hIueUA6gGxto80M/I/v5wfROqJwtrejJs6PjgZYiJMJIyoDE5Vl8B5SGR7a1Tp9g=
  - secure: b+q858M9tChCoGfmDqq8nRtR3r5A0RXDxPK+nHal0RSbsdo/ebahwvq85wfnOukClyv+9bsUSP4hDsmWGGzSZTzAK5UY0nvHCs3v9j5wyCpknq2V6QN9zEaI+RhyFivjtWV86zDegOyO4XOdqkvele2qLZJ3SjUe7O2wMSg7RNM=
  - secure: REdUnayV5qdFAPRi0D/iSDQ6IEW4upf1EELmjO2rxHl+yCV75J8iASjYspQkHqynAJLW+FZb3AYj+T5aql35jsTvqBYdzbspQbXyvmDHi9mSMKc6G/DUHK9/3q8SlislT5xdEkddu7uIIMmkjnV6NXJaGEZePOeasS2MxG5zE9U=
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
- npm test
- npm run build
after_success:
- codeclimate < coverage/lcov.info
- test "$TRAVIS_PULL_REQUEST" = "false" && test "$TRAVIS_BRANCH" = "master" && npm run build && npm run deploy
cache:
  directories:
  - bower_components
  - node_modules
