language: node_js
node_js: --lts # LTS
cache: yarn
before_script:
  - yarn lint
install:
  - yarn install --ignore-scripts # Prevent flow-typed update
script:
  - yarn test --coverage
after_success:
  - codecov
